#!/usr/bin/env bash
set -euo pipefail

# Temporary quick multimachine smoke test.
# - Part 4: quick direct test with 1 worker
# - Part 5: quick indirect test with 1 worker
# - Part 6: quick hotspot test with 1 worker
# - Part 7: run multimachine fault injection as-is
#
# Usage:
#   bash scripts/temp_quick_multimachine_smoke.sh <server_ip> <remote_servers> [rabbitmq_ip] [rabbitmq_user] [rabbitmq_pass]
#
# Example:
#   bash scripts/temp_quick_multimachine_smoke.sh \
#     192.168.1.100 \
#     "192.168.1.101:8001 192.168.1.101:8002" \
#     192.168.1.100 sduser sdpass123

if [[ $# -lt 2 ]]; then
    echo "Usage: bash scripts/temp_quick_multimachine_smoke.sh <server_ip> <remote_servers> [rabbitmq_ip] [rabbitmq_user] [rabbitmq_pass]" >&2
    exit 1
fi

SERVER_IP="$1"
REMOTE_SERVERS="$2"
RABBITMQ_IP="${3:-$SERVER_IP}"
RABBITMQ_USER="${4:-${RABBITMQ_USER:-guest}}"
RABBITMQ_PASS="${5:-${RABBITMQ_PASS:-guest}}"
RABBITMQ_URL="amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@${RABBITMQ_IP}:5672/%2F"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

UNNUMBERED_BENCH="${PROJECT_ROOT}/benchmarks/benchmark_unnumbered_20000.txt"
NUMBERED_BENCH="${PROJECT_ROOT}/benchmarks/benchmark_numbered_60000.txt"
HOTSPOT_BENCH="${PROJECT_ROOT}/benchmarks/benchmark_numbered_hotspot_80_5.txt"

# Quick sample sizes
UNNUMBERED_LINES="${QUICK_UNNUMBERED_LINES:-2000}"
NUMBERED_LINES="${QUICK_NUMBERED_LINES:-2000}"

TMP_DIR="$(mktemp -d)"

restore_benchmarks() {
    if [[ -f "${TMP_DIR}/benchmark_unnumbered_20000.txt" ]]; then
        cp "${TMP_DIR}/benchmark_unnumbered_20000.txt" "${UNNUMBERED_BENCH}"
    fi
    if [[ -f "${TMP_DIR}/benchmark_numbered_60000.txt" ]]; then
        cp "${TMP_DIR}/benchmark_numbered_60000.txt" "${NUMBERED_BENCH}"
    fi
    rm -rf "${TMP_DIR}"
}

trap restore_benchmarks EXIT

echo "[quick-smoke] Backing up benchmark files"
cp "${UNNUMBERED_BENCH}" "${TMP_DIR}/benchmark_unnumbered_20000.txt"
cp "${NUMBERED_BENCH}" "${TMP_DIR}/benchmark_numbered_60000.txt"

echo "[quick-smoke] Creating reduced benchmark datasets"
head -n "${UNNUMBERED_LINES}" "${TMP_DIR}/benchmark_unnumbered_20000.txt" > "${UNNUMBERED_BENCH}"
head -n "${NUMBERED_LINES}" "${TMP_DIR}/benchmark_numbered_60000.txt" > "${NUMBERED_BENCH}"

echo "[quick-smoke] Part 4 quick (direct, 1 worker)"
sudo env \
    LOCAL_UPSTREAM_HOST="${SERVER_IP}" \
    DIRECT_UPSTREAM_SERVERS="${REMOTE_SERVERS}" \
    TOTAL_WORKERS="1" \
    WORKERS_LIST="1" \
    bash "${SCRIPT_DIR}/run_part4_multimachine_scaling_redis.sh"

echo "[quick-smoke] Part 5 quick (indirect, 1 worker)"
sudo env \
    LOCAL_UPSTREAM_HOST="${SERVER_IP}" \
    DIRECT_UPSTREAM_SERVERS="${REMOTE_SERVERS}" \
    TOTAL_WORKERS="1" \
    WORKERS_LIST="1" \
    RABBITMQ_URL="${RABBITMQ_URL}" \
    bash "${SCRIPT_DIR}/run_part5_multimachine_scaling_rabbit.sh"

echo "[quick-smoke] Part 6 quick (hotspot, 1 worker, 1 repeat)"
sudo env \
    LOCAL_UPSTREAM_HOST="${SERVER_IP}" \
    DIRECT_UPSTREAM_SERVERS="${REMOTE_SERVERS}" \
    TOTAL_WORKERS="1" \
    RABBITMQ_URL="${RABBITMQ_URL}" \
    REPEATS="1" \
    bash "${SCRIPT_DIR}/run_part6_multimachine_hotspot_experiment.sh"

echo "[quick-smoke] Restoring original benchmark datasets before Part 7"
cp "${TMP_DIR}/benchmark_unnumbered_20000.txt" "${UNNUMBERED_BENCH}"
cp "${TMP_DIR}/benchmark_numbered_60000.txt" "${NUMBERED_BENCH}"

# Keep Part 7 as-is (multimachine defaults and behavior).
echo "[quick-smoke] Part 7 as-is (multimachine fault injection)"
sudo env \
    LOCAL_UPSTREAM_HOST="${SERVER_IP}" \
    DIRECT_UPSTREAM_SERVERS="${REMOTE_SERVERS}" \
    RABBITMQ_URL="${RABBITMQ_URL}" \
    bash "${SCRIPT_DIR}/run_part7_multimachine_fault_injection.sh"

echo "[quick-smoke] Completed"
echo "[quick-smoke] Results:"
echo "  - ${PROJECT_ROOT}/results/direct_scaling_results.csv"
echo "  - ${PROJECT_ROOT}/results/indirect_scaling_results.csv"
echo "  - ${PROJECT_ROOT}/results/hotspot_comparison_results.csv"
echo "  - ${PROJECT_ROOT}/results/fault_injection_results.csv"
echo "  - ${HOTSPOT_BENCH} (regenerated by part 6)"
